solo_controller:
  type: solo_controller/SoloController
  joint:
    # Front Left
    - FL_HAA
    - FL_HFE
    - FL_KFE
    # Front Right
    - FR_HAA
    - FR_HFE
    - FR_KFE
    # Hind Left
    - HL_HAA
    - HL_HFE
    - HL_KFE
    # Hind Right
    - HR_HAA
    - HR_HFE
    - HR_KFE
  gain:
    # TODO(JaehyunShim): Temporarily set randon pid gains. Rewrite.
    # Front Left
    FL_HAA:
      pid: {p: 300.0, i: 0, d: 50.0, i_clamp: 0, antiwindup: false}
    FL_HFE:
      pid: {p: 100.0, i: 0, d: 20.0, i_clamp: 0, antiwindup: false}
    FL_KFE:
      pid: {p: 100.0, i: 0, d: 20.0, i_clamp: 0, antiwindup: false}
    # Front Right
    FR_HAA:
      pid: {p: 300.0, i: 0, d: 50.0, i_clamp: 0, antiwindup: false}
    FR_HFE:
      pid: {p: 100.0, i: 0, d: 20.0, i_clamp: 0, antiwindup: false}
    FR_KFE:
      pid: {p: 100.0, i: 0, d: 20.0, i_clamp: 0, antiwindup: false}
    # Hind Left
    HL_HAA:
      pid: {p: 300.0, i: 0, d: 50.0, i_clamp: 0, antiwindup: false}
    HL_HFE:
      pid: {p: 100.0, i: 0, d: 20.0, i_clamp: 0, antiwindup: false}
    HL_KFE:
      pid: {p: 100.0, i: 0, d: 20.0, i_clamp: 0, antiwindup: false}
    # Hind Right
    HR_HAA:
      pid: {p: 300.0, i: 0, d: 50.0, i_clamp: 0, antiwindup: false}
    HR_HFE:
      pid: {p: 100.0, i: 0, d: 20.0, i_clamp: 0, antiwindup: false}
    HR_KFE:
      pid: {p: 100.0, i: 0, d: 20.0, i_clamp: 0, antiwindup: false}
  imu: imu
