# Note
# ------------------------------------------------
# Parameters in this file are for gazebo simulator
# ------------------------------------------------

solo_controller:
  type: solo_controller/SoloController
  joint:
    # Front Left
    - FL_HAA
    - FL_HFE
    - FL_KFE
    # Front Right
    - FR_HAA
    - FR_HFE
    - FR_KFE
    # Hind Left
    - HL_HAA
    - HL_HFE
    - HL_KFE
    # Hind Right
    - HR_HAA
    - HR_HFE
    - HR_KFE
  gain:
    # Dynamic reconfigure for PD gain parameters is implemented in solo_controller.
    # Use rqt_reconfigure to tune PD gains if needed.
    # TODO(JaehyunShim): Check if PD gains for each leg can be the same
    # Currently, PD gain can be tuned different for each motor (motor condition etc.)
    # Front Left
    FL_HAA:
      pid: {p: 4.4, d: 0.44}
    FL_HFE:
      pid: {p: 0.27, d: 0.027}
    FL_KFE:
      pid: {p: 0.19, d: 0.019}
    # Front Right
    FR_HAA:
      pid: {p: 4.4, d: 0.44}
    FR_HFE:
      pid: {p: 0.27, d: 0.027}
    FR_KFE:
      pid: {p: 0.19, d: 0.019}
    # Hind Left
    HL_HAA:
      pid: {p: 4.4, d: 0.44}
    HL_HFE:
      pid: {p: 0.27, d: 0.027}
    HL_KFE:
      pid: {p: 0.19, d: 0.019}
    # Hind Right
    HR_HAA:
      pid: {p: 4.4, d: 0.44}
    HR_HFE:
      pid: {p: 0.27, d: 0.027}
    HR_KFE:
      pid: {p: 0.19, d: 0.019}
