solo_controller:
  type: solo_controller/SoloController
  joint:
    # Front Left
    - FL_HAA
    - FL_HFE
    - FL_KFE
    # Front Right
    - FR_HAA
    - FR_HFE
    - FR_KFE
    # Hind Left
    - HL_HAA
    - HL_HFE
    - HL_KFE
    # Hind Right
    - HR_HAA
    - HR_HFE
    - HR_KFE
  gain:
    # TODO(JaehyunShim): Temporarily set random pid gains. Rewrite.
    # Front Left
    FL_HAA:
      pid: {p: 0.6, d: 0.1}
    FL_HFE:
      pid: {p: 0.6, d: 0.1}
    FL_KFE:
      pid: {p: 0.6, d: 0.1}
    # Front Right
    FR_HAA:
      pid: {p: 0.6, d: 0.1}
    FR_HFE:
      pid: {p: 0.6, d: 0.1}
    FR_KFE:
      pid: {p: 0.6, d: 0.1}
    # Hind Left
    HL_HAA:
      pid: {p: 0.6, d: 0.1}
    HL_HFE:
      pid: {p: 0.6, d: 0.1}
    HL_KFE:
      pid: {p: 0.6, d: 0.1}
    # Hind Right
    HR_HAA:
      pid: {p: 0.6, d: 0.1}
    HR_HFE:
      pid: {p: 0.6, d: 0.1}
    HR_KFE:
      pid: {p: 0.6, d: 0.1}
