// TODO(JaehyunShim): Write copyright
//
// Copyright (c) 2021, University of Edinburgh
//
//
// Check what license will be used.
//
//

#ifndef SOLO_TELEOP__SOLO_TELEOP_JOYSTICK_HPP_
#define SOLO_TELEOP__SOLO_TELEOP_JOYSTICK_HPP_

#include <geometry_msgs/Twist.h>
#include <ros/ros.h>
#include <sensor_msgs/Joy.h>

namespace solo_teleop
{
class SoloTeleopJoystick
{
public:
  SoloTeleopJoystick();
  ~SoloTeleopJoystick();

private:
  // Forward/Backward Linear
  double fb_lin_vel_limit_;
  double fb_lin_vel_step_size_;
  // Left/Right Linear
  double lr_lin_vel_limit_;
  double lr_lin_vel_step_size_;
  // Angular
  double ang_vel_limit_;
  double ang_vel_step_size_;

  // Node Handle
  ros::NodeHandle nh_;
  ros::NodeHandle private_nh_;

  // ROS Publisher
  ros::Publisher cmd_vel_pub_;

  // ROS Subscriber
  ros::Subscriber joy_sub_;
  void joy_callback(const sensor_msgs::Joy::ConstPtr & msg);

  void print_joyop();
  void set_goal(const char * str);
  void print_vel(double lin_vel_ref, double ang_vel_ref);
  void enforce_vel_limit(double & vel, double limit);
};
}  // namespace solo_teleop
#endif  // SOLO_TELEOP__SOLO_TELEOP_JOYSTICK_HPP_
